description "USB Ethernet on the emulated host connection"
start on (stopped network and mounted_userstore)
stop on stopping system
task
emits qemu_usb_network_ready

script
    set -e
    /usr/sbin/qemu-usb-network
    initctl emit qemu_usb_network_ready
end script
