start on started lab126 and started ipcservicemanager
stop on stopping lab126 or stopping ipcservicemanager

export LANG LC_ALL

env LIBC_FATAL_STDERR_=1
env STDERR=/tmp/tzd.err

respawn

pre-start script
    source /etc/upstart/env
    source /etc/upstart/functions

    if [ "$(devcap-get-feature -s maplite reg.available)" != "true" ]; then
        f_log I tzd notLoading
        stop
        exit 0
    fi

    f_log I tzd loading
end script

script
    source /etc/upstart/env
    su framework -c "exec /usr/bin/tzd 2>> $STDERR"
end script

post-stop script
    source /etc/upstart/functions
    libc_scan
end script
