# Keep the emulated Kindle awake while the Cocoa window is in use.

start on started powerd
stop on stopping powerd

task

script
    while ! lipc-set-prop com.lab126.powerd preventScreenSaver 1 \
            >/dev/null 2>&1; do
        sleep 1
    done
    echo "Disabled automatic screensaver for QEMU" > /dev/console || true
end script
