description "Dropbear SSH on the emulated USB and Wi-Fi networks"
start on started filesystems_var_local
stop on (stopping system or stopping filesystems_var_local or ota-update)
respawn
exec /usr/sbin/qemu-sshd
